// Entrypoint for R to initialize the Rust extendr module

#include <R.h>
#include <Rinternals.h>

// Declaration of the extendr init function (generated by extendr)
void R_init_fdars_extendr(DllInfo *dll);

// R package init function
void R_init_fdars(DllInfo *dll) {
    R_init_fdars_extendr(dll);
}
